kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    outgoing:
      prices:
        connector: smallrye-kafka
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.quarkus.kafka.client.serialization.JsonbSerializer